version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/app

hooks:
    # Before
    BeforeInstall:
        - location: scripts/prepare.sh
          timeout: 60
          runas: ubuntu
    AfterInstall:
        - location: scripts/install.sh
          timeout: 180
          runas: ubuntu
    ApplicationStart:
        - location: scripts/start.sh
          timeout: 180
          runas: ubuntu
